accounts:
    # .damai.cn中的cookie完整字符串
    - cookie: ""
      remark: 账号1

      # 轮询判断当前时间是否大于等于可以请求数据的时间, 单位ms
      interval: 30

      # 自定义开抢时间戳, 单位:毫秒。 默认: -1, 自动获取开抢时间。
      request_time: -1

      # 最早提前多少毫秒发包。 开抢剩余时间戳 = 开始售票的时间戳 - 当前时间戳。 当开抢剩余时间戳时间小于submit_time时, 开始发送数据包。
      earliest_submit_time: 5

      # 生成订单成功后, 等待多久再提交订单,  单位毫秒
      wait_for_submit: 10

      # 抢票重试次数
      retry_times: 3

      # 重试间隔 单位毫秒
      retry_interval: 100

      ticket:
        # 需要抢购的门票ID, 门票详情页URL中的itemId.如:https://m.damai.cn/damai/detail/item.html?utm=&itemId=710947802955

        id: "721571231867"

        # 需要抢购的门票数量
        num: 1

        # 需要抢购的场次序号.
        sessions: 1
        
        # 需要抢购的票档序号
        grade: 2

        # 优先购的时长是多少分钟(app优先购开始时间等于h5的开抢时间, 实际上没有优先购资格的需要等10-20分钟不等)。默认: 0, 没有优先购
        priority_purchase_time: 0


        # (暂不可用)配置实名人信息, 类型:数组。默认为空, 自动选前N(购票数量)位实名人。如购买2张票, 需要选择第一位和第三位实名人，则填入[1,3]。
        real_names: []

        # 捡漏配置
        pick_up_leaks:
          # 比如开抢时间12:00, 12:00之前启动程序的会自动进入捡漏模式。
          # 如果在12:00之后才启动程序的, 是否进入捡漏模式，取决于这个配置。单位: 分钟。
          # 默认5分钟, 即12:00 ~ 12:05启动程序的, 如果遇到商品已售空，则进入捡漏模式扫描库存。
          # 对于几个小时前就已经售空的票开捡漏模式是没有意义的。所以这个值不需要设置太大。设大了也没用。
          grace_period_minutes: 5

          # 捡漏票数设置, 默认0, 与上面抢票配置保持一致。
          num: 0

          # 轮询间隔, 单位毫秒
          interval: 2000

          # 轮询次数
          times: 100

          # 票档序号配置, 数组格式。默认空=有票就买, 只购买对应票档, 则填入序号。购买第一档和第三档则配置[1,3], 优先购买低票档。
          grades: []

